C2-practical: Vector< T > Class Template Reference
Vector< T > Class Template Reference
Vector
class for a variable sized vector of any type (any? why not?)
Public Member Functions
Vector (const int N)
constructor creating vector of length N
~Vector ()
destructor deleting data
Vector & operator= (const Vector &other)
assignment operator, sets this = v
size_t size () const
return size of vector
void clear ()
set all entries to zero
const T & operator[] (const int i) const
get value at position i using operator[] (modifiable)
T & operator[] (const int i)
get value at position i using operator[] (modifiable)
T operator* (const ThisType &v) const
scalar product with other vector
T * raw ()
return leak pointer for data (only use for visualization!)
const T * raw () const
return leak pointer for data (only use for visualization!)
void print (std::ostream &s) const
print vector to stream
Protected Member Functions
Vector ()
void resize (const int newSize)
resize vector with new size, old data is lost !!!
Protected Attributes
int N_
size of vector
T * data_
data array
Detailed Description
template<class T>
class Vector< T >
class for a variable sized vector of any type (any? why not?)
Constructor & Destructor Documentation
template<class T> Vector< T >::Vector () inline protected
template<class T> Vector< T >::Vector (const int N) inline
constructor creating vector of length N
Parameters
[in] N length of vector
template<class T> Vector< T >::~Vector () inline
destructor deleting data
Member Function Documentation
template<class T> void Vector< T >::clear () inline
set all entries to zero
template<class T> T Vector< T >::operator* (const ThisType & v) const inline
scalar product with other vector
Parameters
[in] v other vector for evaluating scalar product
Returns
scalar product
template<class T> Vector& Vector< T >::operator= (const Vector< T > & other) inline
assignment operator, sets this = v
Parameters
[in] other vector that is copied
Returns
reference to this
template<class T> const T& Vector< T >::operator[] (const int i) const inline
get value at position i using operator[] (modifiable)
Parameters
[in] i position of value
Returns
const reference to entry i
template<class T> T& Vector< T >::operator[] (const int i) inline
get value at position i using operator[] (modifiable)
Parameters
[in] i position of value
Returns
reference to entry i
template<class T> void Vector< T >::print (std::ostream & s) const inline
print vector to stream
Parameters
s stream that vector is printed to
template<class T> T* Vector< T >::raw () inline
return leak pointer for data (only use for visualization!)
Returns
internal pointer T*
Referenced by cghs().
template<class T> const T* Vector< T >::raw () const inline
return leak pointer for data (only use for visualization!)
Returns
internal pointer const T*
template<class T> void Vector< T >::resize (const int newSize) inline protected
resize vector with new size, old data is lost !!!
Parameters
newSize new size of vector
template<class T> size_t Vector< T >::size () const inline
return size of vector
Returns
size of vector
Referenced by cghs(), Vector< double >::operator*(), and Vector< double >::operator=().
Member Data Documentation
template<class T> T* Vector< T >::data_ protected
data array
Referenced by Vector< double >::Vector().
template<class T> int Vector< T >::N_ protected
size of vector
Referenced by Vector< double >::Vector().