C2-practical: DiscreteFunction< BaseSet > Class Template Reference
DiscreteFunction< BaseSet > Class Template Reference
DiscreteFunction
Discrete Function implementation. A Discrete Function combines the DoF storage with a base function set.
Public Types
typedef BaseSet BaseFunctionSetType
type of base function set
Public Member Functions
DiscreteFunction (const GridType &grid)
constructor creating discrete function
double evaluate (const ElementType &element, const LocalCoordType &lambda) const
evaluate discrete function
GlobalCoordType gradient (const ElementType &element, const LocalCoordType &lambda) const
evaluate the gradient of this discrete function
double evaluate (const ElementType &element, const int i, const LocalCoordType &lambda) const
evaluate one base function
GlobalCoordType gradient (const ElementType &element, const int i, const LocalCoordType &lambda) const
evaluate gradient of base function on element
const BaseFunctionSetType & baseFunctionSet () const
returns reference to base function set
double & dof (const ElementType &element, const int localDof)
DoF mapping from element and local DoF number to global DoF.
const GridType & grid () const
return reference to corresponding grid
size_t size () const
return size of vector
void clear ()
set all entries to zero
const double & operator[] (const int i) const
get value at position i using operator[] (modifiable)
double & operator[] (const int i)
get value at position i using operator[] (modifiable)
double operator* (const ThisType &v) const
scalar product with other vector
double * raw ()
return leak pointer for data (only use for visualization!)
const double * raw () const
return leak pointer for data (only use for visualization!)
void print (std::ostream &s) const
print vector to stream
Protected Member Functions
void resize (const int newSize)
resize vector with new size, old data is lost !!!
Protected Attributes
const GridType & grid_
reference to grid
BaseFunctionSetType base_
base function set
int N_
size of vector
double * data_
data array
Detailed Description
template<class BaseSet>
class DiscreteFunction< BaseSet >
Discrete Function implementation. A Discrete Function combines the DoF storage with a base function set.
Parameters
BaseSet implementation class of the base function set
Member Typedef Documentation
template<class BaseSet> typedef BaseSet DiscreteFunction< BaseSet >::BaseFunctionSetType
type of base function set
Constructor & Destructor Documentation
template<class BaseSet> DiscreteFunction< BaseSet >::DiscreteFunction (const GridType & grid) inline explicit
constructor creating discrete function
Parameters
[in] grid Grid for this discrete function
Member Function Documentation
template<class BaseSet> const BaseFunctionSetType& DiscreteFunction< BaseSet >::baseFunctionSet () const inline
returns reference to base function set
void Vector< double >::clear () inline inherited
set all entries to zero
template<class BaseSet> double& DiscreteFunction< BaseSet >::dof (const ElementType & element, const int localDof) inline
DoF mapping from element and local DoF number to global DoF.
Parameters
[in] element element the DoF is located on
[in] localDof local DoF number
Returns
reference to DoF
template<class BaseSet> double DiscreteFunction< BaseSet >::evaluate (const ElementType & element, const LocalCoordType & lambda) const inline
evaluate discrete function
Parameters
[in] element element the discrete function is evaluated on
[in] lambda local coordinate in element for evaluation
Returns
f(x)
References LinearBaseFunction::evaluate().
template<class BaseSet> double DiscreteFunction< BaseSet >::evaluate (const ElementType & element, const int i, const LocalCoordType & lambda) const inline
evaluate one base function
Parameters
[in] element the element on which to evaluate the base function
[in] i number of base function to evaluate
[in] lambda local coordinate where base function is evaluated
Returns
evaluation of the i-th base function
template<class BaseSet> GlobalCoordType DiscreteFunction< BaseSet >::gradient (const ElementType & element, const LocalCoordType & lambda) const inline
evaluate the gradient of this discrete function
Parameters
[in] element Element on which contains the coordinate to evaluate
[in] lambda local coodrinate of the evaluation point
Returns
gradient of discrete function at given point
template<class BaseSet> GlobalCoordType DiscreteFunction< BaseSet >::gradient (const ElementType & element, const int i, const LocalCoordType & lambda) const inline
evaluate gradient of base function on element
Parameters
[in] element element to evaluate gradient on
[in] i number of base function to evaluate
[in] lambda local coordinate where the gradient of the base function is evaluated
Returns
evaluation of the i-th base function gradient
References GRID::Element< GridImp >::gradientGlobal().
template<class BaseSet> const GridType& DiscreteFunction< BaseSet >::grid () const inline
return reference to corresponding grid
double Vector< double >::operator* (const ThisType & v) const inline inherited
scalar product with other vector
Parameters
[in] v other vector for evaluating scalar product
Returns
scalar product
References Vector< T >::size().
const double & Vector< double >::operator[] (const int i) const inline inherited
get value at position i using operator[] (modifiable)
Parameters
[in] i position of value
Returns
const reference to entry i
double & Vector< double >::operator[] (const int i) inline inherited
get value at position i using operator[] (modifiable)
Parameters
[in] i position of value
Returns
reference to entry i
void Vector< double >::print (std::ostream & s) const inline inherited
print vector to stream
Parameters
s stream that vector is printed to
double * Vector< double >::raw () inline inherited
return leak pointer for data (only use for visualization!)
Returns
internal pointer T*
const double * Vector< double >::raw () const inline inherited
return leak pointer for data (only use for visualization!)
Returns
internal pointer const T*
void Vector< double >::resize (const int newSize) inline protected inherited
resize vector with new size, old data is lost !!!
Parameters
newSize new size of vector
size_t Vector< double >::size () const inline inherited
return size of vector
Returns
size of vector
Member Data Documentation
template<class BaseSet> BaseFunctionSetType DiscreteFunction< BaseSet >::base_ protected
base function set
double * Vector< double >::data_ protected inherited
data array
template<class BaseSet> const GridType& DiscreteFunction< BaseSet >::grid_ protected
reference to grid
int Vector< double >::N_ protected inherited
size of vector