C2-practical: LineQuadrature Class Reference
LineQuadrature Class Reference
Quadratures
Quadrature implementation for order = 2 (center of edges)
Public Member Functions
LineQuadrature ()
constructor creating a quadrature
int nop () const
return number of quadrature points
double weight (const int qp)
return weight for quadrature point
const LocalCoordType & point (const int qp) const
return local coordinates for quadrature point
Protected Member Functions
void addQuadraturePoint (const LocalCoordType &point, const double weight)
add (point,weight) pair to quadrature
Detailed Description
Quadrature implementation for order = 2 (center of edges)
Constructor & Destructor Documentation
LineQuadrature::LineQuadrature () inline
constructor creating a quadrature
References Quadrature::addQuadraturePoint(), Quadrature::point(), and Quadrature::weight().
Member Function Documentation
void Quadrature::addQuadraturePoint (const LocalCoordType & point, const double weight) inline protected inherited
add (point,weight) pair to quadrature
Parameters
[in] point local coordinates of quadrature point
[in] weight weight for quadrature point
Referenced by LineQuadrature(), PointQuadrature::PointQuadrature(), and ThirdQuadrature::ThirdQuadrature().
int Quadrature::nop () const inline inherited
return number of quadrature points
Returns
number of quadrature points
const LocalCoordType& Quadrature::point (const int qp) const inline inherited
return local coordinates for quadrature point
Parameters
[in] qp number of quadrature point that local coordinates are returned for
Returns
local coordinates for quadrature point qp
Referenced by LineQuadrature(), PointQuadrature::PointQuadrature(), and ThirdQuadrature::ThirdQuadrature().
double Quadrature::weight (const int qp) inline inherited
return weight for quadrature point
Parameters
[in] qp number of quadrature point that weight is returned for
Returns
weight for quadrature point qp
Referenced by LineQuadrature(), PointQuadrature::PointQuadrature(), and ThirdQuadrature::ThirdQuadrature().