C2-practical: GRID::Element< GridImp > Class Template Reference
GRID::Element< GridImp > Class Template Reference
Grid
The Element class provides all information needed on single elements.
Public Types
enum { dimension = EntityType :: dimension, dimensionworld = EntityType :: dimensionworld }
dimension of the element
enum { nCorners = dimension + 1 }
number of vertices that are used to build this element
typedef Element< GridImp > ThisType
type of this class
typedef GridImp::EntityType EntityType
entity type that is used to build this element
typedef IntersectionIterator< GridImp > IntersectionIteratorType
type of intersection iterator
Public Member Functions
Element (const GridImp &grid)
constructor ceating empty element
Element (const GridImp &grid, const EntityPointerImp &enPtr)
IntersectionIteratorType ibegin () const
return intersection iterator pointing to the first intersection
const IntersectionIteratorType iend () const
return intersection iterator pointing behind the last intersection
const GlobalCoordType & operator[] (const int i) const
return coordinate of i-th corner
int index (int codim, int local) const
return global index of subentites given local index
GlobalCoordType global (const LocalCoordType &local) const
mapping from local to global coordinate
void gradientGlobal (const LocalCoordType &dphi, GlobalCoordType &gradient) const
mapping of gradient from reference element to element coordinates
double area () const
returns area of element
double integrationElement () const
returns determinant of reference mapping
bool onBoundary (int edge) const
returns if an edge is is part of the boundary
Protected Member Functions
void update (const EntityType &entity)
update to next element
void initBnd () const
Detailed Description
template<class GridImp>
class GRID::Element< GridImp >
The Element class provides all information needed on single elements.
Parameters
GridImp implementation of grid, here the Grid class.
Member Typedef Documentation
template<class GridImp > typedef GridImp :: EntityType GRID::Element< GridImp >::EntityType
entity type that is used to build this element
template<class GridImp > typedef IntersectionIterator<GridImp> GRID::Element< GridImp >::IntersectionIteratorType
type of intersection iterator
template<class GridImp > typedef Element< GridImp > GRID::Element< GridImp >::ThisType
type of this class
Member Enumeration Documentation
template<class GridImp > anonymous enum
dimension of the element
Enumerator
dimension
dimension of the grid
dimensionworld
dimension of the grid
template<class GridImp > anonymous enum
number of vertices that are used to build this element
Enumerator
nCorners
number of corners of the element
Constructor & Destructor Documentation
template<class GridImp > GRID::Element< GridImp >::Element (const GridImp & grid) inline
constructor ceating empty element
template<class GridImp > GRID::Element< GridImp >::Element (const GridImp & grid, const EntityPointerImp & enPtr) inline
References GRID::Element< GridImp >::update().
Member Function Documentation
template<class GridImp > double GRID::Element< GridImp >::area () const inline
returns area of element
Returns
area of element
template<class GridImp > GlobalCoordType GRID::Element< GridImp >::global (const LocalCoordType & local) const inline
mapping from local to global coordinate
Parameters
local local coordinate (in reference element)
Returns
global coordinate (in element), i.e.
References GRID::Element< GridImp >::dimensionworld.
template<class GridImp > void GRID::Element< GridImp >::gradientGlobal (const LocalCoordType & dphi, GlobalCoordType & gradient) const inline
mapping of gradient from reference element to element coordinates
Parameters
dphi gradient with respect to the reference element
gradient return value for the gradient with respect to the element: , where .
References GRID::Element< GridImp >::dimensionworld.
Referenced by DiscreteFunction< BaseSet >::gradient().
template<class GridImp > IntersectionIteratorType GRID::Element< GridImp >::ibegin () const inline
return intersection iterator pointing to the first intersection
Referenced by GRID::Element< GridImp >::initBnd().
template<class GridImp > const IntersectionIteratorType GRID::Element< GridImp >::iend () const inline
return intersection iterator pointing behind the last intersection
Referenced by GRID::Element< GridImp >::initBnd().
template<class GridImp > int GRID::Element< GridImp >::index (int codim, int local) const inline
return global index of subentites given local index
Parameters
codim codimension of subentity
local local number of subentity
Returns
global index
References GRID::Element< GridImp >::nCorners.
Referenced by LinearBaseFunction::map().
template<class GridImp > void GRID::Element< GridImp >::initBnd () const inline protected
References GRID::Intersection< GridImp >::boundary(), GRID::Element< GridImp >::ibegin(), GRID::Element< GridImp >::iend(), and GRID::Intersection< GridImp >::numberInSelf().
Referenced by GRID::Element< GridImp >::onBoundary().
template<class GridImp > double GRID::Element< GridImp >::integrationElement () const inline
returns determinant of reference mapping
Returns
the determinant of the reference mapping
template<class GridImp > bool GRID::Element< GridImp >::onBoundary (int edge) const inline
returns if an edge is is part of the boundary
Parameters
edge edge number in element
Returns
true if on boundary
References GRID::Element< GridImp >::dimension, and GRID::Element< GridImp >::initBnd().
template<class GridImp > const GlobalCoordType& GRID::Element< GridImp >::operator[] (const int i) const inline
return coordinate of i-th corner
Parameters
i number of corner of element
Returns
coordinate vector of i-th corner
References GRID::Element< GridImp >::nCorners.
template<class GridImp > void GRID::Element< GridImp >::update (const EntityType & entity) inline protected
update to next element
Parameters
[in] enPtr dune entity that is wrapped
References GRID::Element< GridImp >::dimension, GRID::Element< GridImp >::dimensionworld, and GRID::Element< GridImp >::nCorners.
Referenced by GRID::Element< GridImp >::Element(), GRID::Iterator< GridImp, GridImp::IteratorImp, Element< GridImp > >::Iterator(), GRID::Iterator< GridImp, GridImp::IteratorImp, Element< GridImp > >::operator++(), and GRID::Iterator< GridImp, GridImp::IteratorImp, Element< GridImp > >::operator=().