C2-practical: SparseMatrix< T > Class Template Reference
SparseMatrix< T > Class Template Reference
Matrix
matrix implementation that stores entries in compressed-row storage (CRS)
Public Member Functions
SparseMatrix (const int rows, const int nonZero)
constructor
~SparseMatrix ()
destructor
void add (const int row, const int column, const T &value)
add value to matrix entry
void set (const int row, const int column, const T value)
set matrix entry to certain value
void setDiag (const int row, const T value=1)
set diagonal entry to certain value and remove all other column entries for this row
int row () const
return number of rows
void print () const
print matrix to standard out stream, for debugging only
void mult (const T *v, T *w) const
matrix-vector multiplication, i.e.
Detailed Description
template<class T>
class SparseMatrix< T >
matrix implementation that stores entries in compressed-row storage (CRS)
Constructor & Destructor Documentation
template<class T > SparseMatrix< T >::SparseMatrix (const int rows, const int nonZero) inline
constructor
Parameters
rows number of rows
nonZero maximal number of non-zeros per row
template<class T > SparseMatrix< T >::~SparseMatrix () inline
destructor
Member Function Documentation
template<class T > void SparseMatrix< T >::add (const int row, const int column, const T & value) inline
add value to matrix entry
Parameters
row row of matrix entry
column column of matrix entry
value value to add
template<class T > void SparseMatrix< T >::mult (const T * v, T * w) const inline
matrix-vector multiplication, i.e.
Parameters
[in] v vector to multiply
[out] w result vector
References SparseMatrix< T >::row().
template<class T > void SparseMatrix< T >::print () const inline
print matrix to standard out stream, for debugging only
template<class T > int SparseMatrix< T >::row () const inline
return number of rows
Returns
number of rows
Referenced by SparseMatrix< T >::mult(), and SparseMatrix< T >::setDiag().
template<class T > void SparseMatrix< T >::set (const int row, const int column, const T value) inline
set matrix entry to certain value
Parameters
row row of matrix entry
column column of matrix entry
value value to set to matrix entry
template<class T > void SparseMatrix< T >::setDiag (const int row, const T value = 1) inline
set diagonal entry to certain value and remove all other column entries for this row
Parameters
row row of matrix entry
value value to set to matrix entry (default value is 1)
References SparseMatrix< T >::row().