C2-practical: Problem2_1 Class Reference
Problem2_1 Class Reference abstract
Problem
Public Member Functions
Problem2_1 (double a)
virtual ~Problem2_1 ()
virtual double u (const GlobalCoordType &x) const =0
return value of exact solution
virtual double f (const GlobalCoordType &x) const =0
return value of right hand side
virtual double g (const GlobalCoordType &x) const
return value of Dirichlet boundary conditions (default implementation return u(x))
virtual void du (const GlobalCoordType &x, GlobalCoordType &du) const =0
return derivative of u
virtual double lambda () const
return constant in front of zero order term
virtual GlobalCoordType b () const
return constant in front of advection term
virtual bool useDirichlet () const
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
virtual bool Q4 () const
Constructor & Destructor Documentation
Problem2_1::Problem2_1 (double a) inline
virtual Problem2_1::~Problem2_1 () inline virtual
Member Function Documentation
virtual GlobalCoordType Problem::b () const inline virtual inherited
return constant in front of advection term
Returns
virtual void Problem::du (const GlobalCoordType & x, GlobalCoordType & du) const pure virtual inherited
return derivative of u
Parameters
[in] x global coordinate to evaluate du
[out] du the gradient of the function u
Implemented in Problem5, Problem2019_Ass1_5, Problem4, Problem2019_Ass1_4, Problem2019_Ass2_3, Problem3, Problem2019_Ass1_2_3, Problem2, Problem2019_Ass1_1, Problem2019_Ass2_2, Problem1, ProblemSqrt, ProblemSin, ProblemC1, and Problem2019_Ass2_1.
Referenced by Problem::g().
virtual double Problem::f (const GlobalCoordType & x) const pure virtual inherited
return value of right hand side
Parameters
[in] x global coordinate to evaluate f
Returns
f(x)
Implemented in Problem5, Problem2019_Ass1_5, Problem4, Problem2019_Ass1_4, Problem2019_Ass2_3, Problem3, Problem2019_Ass1_2_3, Problem2, Problem2019_Ass1_1, Problem2019_Ass2_2, Problem1, ProblemSqrt, ProblemSin, ProblemC1, and Problem2019_Ass2_1.
Referenced by Problem::~Problem().
virtual double Problem::g (const GlobalCoordType & x) const inline virtual inherited
return value of Dirichlet boundary conditions (default implementation return u(x))
Parameters
[in] x global coordinate to evaluate g
Returns
g(x)
References Problem::du(), and Problem::u().
virtual double Problem::lambda () const inline virtual inherited
return constant in front of zero order term
Returns
Reimplemented in Problem2019_Ass2_3, Problem2019_Ass2_2, and Problem2019_Ass2_1.
virtual bool Problem::Q4 () const inline virtual inherited
Reimplemented in Problem2019_Ass2_3.
virtual double Problem::u (const GlobalCoordType & x) const pure virtual inherited
return value of exact solution
Parameters
[in] x global coordinate to evaluate u
Returns
u(x)
Implemented in Problem5, Problem2019_Ass1_5, Problem4, Problem2019_Ass1_4, Problem2019_Ass2_3, Problem3, Problem2019_Ass1_2_3, Problem2, Problem2019_Ass1_1, Problem2019_Ass2_2, Problem1, ProblemSqrt, ProblemSin, ProblemC1, and Problem2019_Ass2_1.
Referenced by Problem::g(), and Problem::~Problem().
virtual bool Problem::useDirichlet () const inline virtual inherited
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
Reimplemented in Problem2019_Ass2_3, Problem2019_Ass2_2, and Problem2019_Ass2_1.