C2-practical: Solver
Solver
Functions
template<class MATRIX >
int cghs (const unsigned int N, const MATRIX &A, const double *b, double *x, const double eps, const bool detailed=false)
CG scheme after Hestenes und Stiefel.
template<class T , class MATRIX >
int cghs (const MATRIX &A, const Vector< T > &b, Vector< T > &x, const double eps, const bool detailed=false)
CG scheme after Hestenes und Stiefel.
Detailed Description
Function Documentation
template<class MATRIX > int cghs (const unsigned int N, const MATRIX & A, const double * b, double * x, const double eps, const bool detailed = false) inline
CG scheme after Hestenes und Stiefel.
Parameters
N number of unknowns
A matrix (implement mult method for this matrix)
b right hand side
x unknown
eps error bound
detailed flag for toggeling output
Referenced by cghs().
template<class T , class MATRIX > int cghs (const MATRIX & A, const Vector< T > & b, Vector< T > & x, const double eps, const bool detailed = false) inline
CG scheme after Hestenes und Stiefel.
Parameters
A matrix (implement mult method for this matrix)
b right hand side
x unknown
eps error bound
detailed flag for toggeling output (default is false)
References cghs(), Vector< T >::raw(), and Vector< T >::size().