C2-practical: Problem
Problem
Classes
struct Problem
Problem Interface to setup different problems.
class ProblemSin
Sinus Problem for Interpolation.
class Problem1
class Problem2
class Problem3
class Problem4
class Problem5
class ProblemC1
C0 problem.
class ProblemSqrt
Sqrt Problem for Interpolation.
class Problem2019_Ass1_1
class Problem2019_Ass1_2_3
class Problem2019_Ass1_4
Linear Problem for Interpolation.
class Problem2019_Ass1_5
H^2^1 Problem for Interpolation.
class Problem2_1
class Problem2019_Ass2_1
C0 problem.
class Problem2019_Ass2_2
class Problem2019_Ass2_3
Functions
Problem2019_Ass2_1::Problem2019_Ass2_1 ()
virtual Problem2019_Ass2_1::~Problem2019_Ass2_1 ()
double Problem2019_Ass2_1::u (const GlobalCoordType &x) const
return value of exact solution
void Problem2019_Ass2_1::du (const GlobalCoordType &x, GlobalCoordType &du) const
return derivative of u
double Problem2019_Ass2_1::f (const GlobalCoordType &x) const
return value of right hand side
double Problem2019_Ass2_1::lambda () const
return constant in front of zero order term
bool Problem2019_Ass2_1::useDirichlet () const
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
Problem2019_Ass2_2::Problem2019_Ass2_2 ()
virtual Problem2019_Ass2_2::~Problem2019_Ass2_2 ()
double Problem2019_Ass2_2::u (const GlobalCoordType &x) const
return value of exact solution
void Problem2019_Ass2_2::du (const GlobalCoordType &x, GlobalCoordType &du) const
return derivative of u
double Problem2019_Ass2_2::f (const GlobalCoordType &x) const
return value of right hand side
double Problem2019_Ass2_2::lambda () const
return constant in front of zero order term
bool Problem2019_Ass2_2::useDirichlet () const
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
Problem2019_Ass2_3::Problem2019_Ass2_3 ()
virtual Problem2019_Ass2_3::~Problem2019_Ass2_3 ()
double Problem2019_Ass2_3::u (const GlobalCoordType &x) const
return value of exact solution
void Problem2019_Ass2_3::du (const GlobalCoordType &x, GlobalCoordType &du) const
return derivative of u
double Problem2019_Ass2_3::f (const GlobalCoordType &x) const
return value of right hand side
double Problem2019_Ass2_3::lambda () const
return constant in front of zero order term
bool Problem2019_Ass2_3::useDirichlet () const
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
bool Problem2019_Ass2_3::Q4 () const
Variables
const double Problem2019_Ass2_3::b = 0.6
const double Problem2019_Ass2_3::a = 0.9
Detailed Description
Function Documentation
void Problem2019_Ass2_1::du (const GlobalCoordType & x, GlobalCoordType & du) const inline virtual
return derivative of u
Parameters
[in] x global coordinate to evaluate du
[out] du the gradient of the function u
Implements Problem.
void Problem2019_Ass2_2::du (const GlobalCoordType & x, GlobalCoordType & du) const inline virtual
return derivative of u
Parameters
[in] x global coordinate to evaluate du
[out] du the gradient of the function u
Implements Problem.
void Problem2019_Ass2_3::du (const GlobalCoordType & x, GlobalCoordType & du) const inline virtual
return derivative of u
Parameters
[in] x global coordinate to evaluate du
[out] du the gradient of the function u
Implements Problem.
double Problem2019_Ass2_1::f (const GlobalCoordType & x) const inline virtual
return value of right hand side
Parameters
[in] x global coordinate to evaluate f
Returns
f(x)
Implements Problem.
References Problem2019_Ass2_1::u().
double Problem2019_Ass2_2::f (const GlobalCoordType & x) const inline virtual
return value of right hand side
Parameters
[in] x global coordinate to evaluate f
Returns
f(x)
Implements Problem.
References Problem2019_Ass2_1::u().
double Problem2019_Ass2_3::f (const GlobalCoordType & x) const inline virtual
return value of right hand side
Parameters
[in] x global coordinate to evaluate f
Returns
f(x)
Implements Problem.
References Problem2019_Ass2_1::u().
double Problem2019_Ass2_1::lambda () const inline virtual
return constant in front of zero order term
Returns
Reimplemented from Problem.
double Problem2019_Ass2_2::lambda () const inline virtual
return constant in front of zero order term
Returns
Reimplemented from Problem.
double Problem2019_Ass2_3::lambda () const inline virtual
return constant in front of zero order term
Returns
Reimplemented from Problem.
Problem2019_Ass2_1::Problem2019_Ass2_1 () inline
Problem2019_Ass2_2::Problem2019_Ass2_2 () inline
Problem2019_Ass2_3::Problem2019_Ass2_3 () inline
bool Problem2019_Ass2_3::Q4 () const inline virtual
Reimplemented from Problem.
double Problem2019_Ass2_1::u (const GlobalCoordType & x) const inline virtual
return value of exact solution
Parameters
[in] x global coordinate to evaluate u
Returns
u(x)
Implements Problem.
Referenced by Problem2019_Ass2_1::f(), Problem2019_Ass2_2::f(), and Problem2019_Ass2_3::f().
double Problem2019_Ass2_2::u (const GlobalCoordType & x) const inline virtual
return value of exact solution
Parameters
[in] x global coordinate to evaluate u
Returns
u(x)
Implements Problem.
double Problem2019_Ass2_3::u (const GlobalCoordType & x) const inline virtual
return value of exact solution
Parameters
[in] x global coordinate to evaluate u
Returns
u(x)
Implements Problem.
bool Problem2019_Ass2_1::useDirichlet () const inline virtual
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
Reimplemented from Problem.
bool Problem2019_Ass2_2::useDirichlet () const inline virtual
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
Reimplemented from Problem.
bool Problem2019_Ass2_3::useDirichlet () const inline virtual
return true if dirichlet data is to be used on full boundary. In case that false is returned Neumann zero boundary connditions are used - then should be greater than zero.
Reimplemented from Problem.
virtual Problem2019_Ass2_1::~Problem2019_Ass2_1 () inline virtual
virtual Problem2019_Ass2_2::~Problem2019_Ass2_2 () inline virtual
virtual Problem2019_Ass2_3::~Problem2019_Ass2_3 () inline virtual
Variable Documentation
const double Problem2019_Ass2_3::a = 0.9
const double Problem2019_Ass2_3::b = 0.6